# Generated by Django 2.1.2 on 2018-10-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
    ]
