# Generated by Django 2.1.2 on 2018-10-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator', '0002_news_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='year_in_school',
        ),
    ]
